version: "3.9"
volumes:
  node_modules_volume:
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  app:
    build:
      context: ./backend
      dockerfile: ./../infra/django/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build:
      context: ./frontend
      dockerfile: ./../infra/nuxt/Dockerfile
    image: nuxt_app_image
    ports:
      - "3000:3000"
    command: yarn dev
    volumes:
      - "./frontend:/frontend"
      - node_modules_volume:/front/node_modules
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
